# Generated by Django 5.0.4 on 2024-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('stats', models.CharField(max_length=255)),
                ('abilities', models.CharField(max_length=255)),
                ('sprites', models.CharField(max_length=255)),
                ('moves', models.CharField(max_length=255)),
            ],
        ),
    ]
