# Generated by Django 5.0.4 on 2024-04-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_held_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='held_items',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='moves',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sprites',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='stats',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.TextField(),
        ),
    ]
