# Generated by Django 5.0.4 on 2024-04-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_abilities_alter_pokemon_held_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='held_items',
            new_name='held_item',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='moves',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sprites',
            field=models.URLField(),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.type')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemon.type'),
        ),
    ]
