# Generated by Django 5.0.4 on 2024-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_ability_type_rename_held_items_pokemon_held_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_stat', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='stats',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.ManyToManyField(to='pokemon.stat'),
        ),
    ]
