# Generated by Django 5.0.4 on 2024-04-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_alter_ability_name_alter_move_name_alter_pokemon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='accuracy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='pp',
            field=models.IntegerField(null=True),
        ),
    ]
