# Generated by Django 5.0.4 on 2024-05-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_remove_pokemon_stats_pokemon_attack_pokemon_defense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon1', to='pokemon.pokemon')),
                ('pokemon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon2', to='pokemon.pokemon')),
                ('pokemon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon3', to='pokemon.pokemon')),
                ('pokemon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon4', to='pokemon.pokemon')),
                ('pokemon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon5', to='pokemon.pokemon')),
                ('pokemon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon6', to='pokemon.pokemon')),
            ],
        ),
    ]
