# Generated by Django 5.0.4 on 2024-05-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ability1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability1', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='ability2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability2', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='ability3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability3', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='ability4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability4', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='ability5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability5', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='ability6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability6', to='pokemon.ability'),
        ),
        migrations.AddField(
            model_name='team',
            name='move1_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move1_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move1_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move1_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move1_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move1_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move1_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move1_4', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move2_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move2_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move2_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move2_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move2_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move2_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move2_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move2_4', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move3_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move3_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move3_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move3_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move3_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move3_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move3_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move3_4', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move4_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move4_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move4_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move4_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move4_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move4_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move4_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move4_4', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move5_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move5_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move5_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move5_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move5_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move5_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move5_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move5_4', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move6_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move6_1', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move6_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move6_2', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move6_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move6_3', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='team',
            name='move6_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move6_4', to='pokemon.move'),
        ),
    ]
